### PR TITLE
Simplifies YAML for redirect_to

### PR DESCRIPTION
**Pull request by dmalan**
Perhaps simpler to describe the value of `redirect_to` as a string rather than as a single-valued list? Seems to work well if provided as a string!

### CODE REVIEW

**Comment by dmalan** [comment]
Just curious, did this not resonate, @DirtyF?

**Comment by DirtyF** [comment]
@dmalan my bad, I misread.

**Comment by DirtyF** [comment]
@jekyllbot: merge +docs

**Comment by dmalan** [comment]
Ah, excellent, thanks!

**Pull request merged**
