### PR TITLE
run javascript at first to avoid splash

### PR DESCRIPTION
**Pull request by NewFuture**
Just changed the order of the scripts.
In most browsers (such as chrome), it will execute the javascript before page rendering.
So that the page will redirect without the splash white screen :)

### CODE REVIEW

**Comment by NewFuture** [comment]
Of course.
But it will parse the `refresh` meta firstly, which is unnecessary when the JavaScript is enabled.
We just what to it redirect as soon as possible 😄

**Comment by pathawks** [comment]
It seems the `<meta>` _should_ be parsed first, and the JavaScript only serve as a backup incase something weird happens. Is that not what is happening?

**Comment by NewFuture** [comment]
Not exactly.  
The `script` should be paresed at first and the `<meta>` is a back.

Most of the browsers will parse and execute the inline JavaScript as document order.
This JavaScript code will be executed immediately when parsed. Then it the browser will redirect and stop to parse and render the HTML document.

## For an example

Try this code in Chrome
```html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script>
        alert(1);
        location="https://github.com/";
    </script>
    <title>Title</title>
    <meta http-equiv="refresh" content="0; url=http://jekyllrb.com/">
    <script>
        alert(2);
    </script>
</html>
```
It will alert and redirect to `https://github.com/` immediately; and  it will not show the `Title` or execute the second JavaScript bock (`alert(2)`) or redirect ro `http://jekyllrb.com/`. 


## For  [current version](https://github.com/jekyll/jekyll-redirect-from/blob/2f0974b5f2015aa6be5f68cb012d4790d247939b/lib/jekyll-redirect-from/redirect.html#L10)

It will display a screen like this screenshot, before jumping to new URL.
image

## For this PR

It will not show this screen unless the JavaScript is disabled (the `<meta>` is a backup). 
If the network is slow it will just show the `Redirecting…` in browser title (without painting the window).
I think this this way it better for  both user experience and performance.

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
