### PR TITLE
use original destination path for Page construction

### LINKED ISSUE #107: redirect_to appears not to work
Hello, we've been using this product for a while now and recently noticed all of our pages that use `redirect_to` are not redirecting to the expected destination. 

As an example: this URL https://18f.gsa.gov/tags/day%20in%20the%20life/ should redirect to this url: https://18f.gsa.gov/tags/day-in-the-life/ but as you can see [it generates a blank page instead](https://18f.gsa.gov/tags/day%20in%20the%20life/). Here's [the source file that generates that page](https://github.com/18F/18f.gsa.gov/blob/staging/pages/tags/day%20in%20the%20life.md).

 I haven't tested it with _all_ the pages using `redirect_to` but [`/tags/demo day/`](https://18f.gsa.gov/tags/demo%20day/) and [`/how we work/`](https://18f.gsa.gov/tags/how%20we%20work/) are also failing. 

Pages using [`redirect_from` appear to be working correctly](https://18f.gsa.gov/2016/04/07/making-more-consistent-decisions-with-design-principles-a-new-18f-guide/).

### PR DESCRIPTION
**Pull request by koron**
instead of URL.

This will fix #107

### CODE REVIEW

**Comment by benbalter** [comment]
@jekyll/plugin-core I've recreated https://github.com/jekyll/jekyll-redirect-from/issues/107 in the wild. Any objection to merging this PR?

Steps to reproduce:

1. Create a new page `foo.html` with permalink: `/foo/`
2. Add `jekyll_redirect_to: /bar/`

Expected

File `/foo/index.html` exists and is a redirect

Actual:

File `/foo` exists, and is a redirect.

**Comment by benbalter** [comment]
Err actual, should probably use https://github.com/jekyll/jekyll-redirect-from/pull/111 instead, which has tests.

**Comment by parkr** [comment]
@benbalter #111 does the same?

**Comment by benbalter** [comment]
I believe #111 fixes this. Thanks @koron!

**Pull request closed without merging**
