### PR TITLE
Rubocop: autocorrect

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @DirtyF.

```text
Rubocop: autocorrect
```

### CODE REVIEW

**Comment by DirtyF** [comment]
Waiting for GitHub Pages to update to latest Jekyll (3.6.2)

**Comment by parkr** [comment]
Restarted the GH_PAGES=true target now that Pages has updated to Jekyll 3.6.2.

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Pull request merged**
