### PR TITLE
Test against Jekyll 3

### PR DESCRIPTION
**Pull request by pathawks**
jekyll/jekyll#3945

### CODE REVIEW

**Comment by pathawks** [comment]
The test chokes when testing with GitHub Pages:
```rspec
Failures:
  1) JekyllRedirectFrom::RedirectPage when determining the write destination of a redirect page meant to be a file knows not to add the index.html if it's not a folder
     Failure/Error: expect(redirect_page.destination("/")).to eql(dest)
       
       expected: "/home/travis/build/jekyll/jekyll-redirect-from/spec/fixtures/_site/posts/12435151125/larry-had-a-little-lamb"
            got: "/posts/12435151125/larry-had-a-little-lamb"
       
       (compared using eql?)
     # ./spec/jekyll_redirect_from/redirect_page_spec.rb:45:in `block (4 levels) in <top (required)>'
  2) JekyllRedirectFrom::RedirectPage when determining the write destination of a redirect page meant to be a dir knows to add the index.html if it's a folder
     Failure/Error: expect(redirect_page.destination("/")).to eql(dest)
       
       expected: "/home/travis/build/jekyll/jekyll-redirect-from/spec/fixtures/_site/posts/1914798137981389/larry-had-a-little-lamb/index.html"
            got: "/posts/1914798137981389/larry-had-a-little-lamb/index.html"
       
       (compared using eql?)
     # ./spec/jekyll_redirect_from/redirect_page_spec.rb:38:in `block (4 levels) in <top (required)>'
Finished in 1.29 seconds (files took 0.31592 seconds to load)
31 examples, 2 failures
```

Clearly the *test* is wrong. Any ideas why?

**Comment by parkr** [comment]
Comparing paths is always annoying. It looks like `#destination` requires the absolute path to dest, perhaps, instead of just `"/"`?

**Comment by pathawks** [comment]
Does it has something to do with safe mode or file system quarantine?

It *only* fails when testing with the **GitHub Pages** gem. In all other cases, `new_redirect_page(permalink)` returns the absolute path, but when testing with gh-pages it returns a relative path.

**Comment by parkr** [comment]
> It only fails when testing with the GitHub Pages gem.

Perhaps it is a failure of Jekyll. I bet we fixed something in 2.5 that GHP's 2.4 isn't getting.

**Comment by pathawks** [comment]
> Perhaps it is a failure of Jekyll. I bet we fixed something in 2.5 that GHP's 2.4 isn't getting.

Yes, I can confirm that the test fails with 2.4 and passes with [2.5.0](https://github.com/jekyll/jekyll/releases/tag/v2.5.0).

So... maybe shouldn't require the gh-pages test to pass for now?

**Comment by parkr** [comment]
Thank you! You're killin it. I appreciate all these PR's.

**Comment by pathawks** [comment]
Happy to help in the small ways I am able :+1:

**Pull request merged**
