### PR TITLE
Avoid documents cache problem

### PR DESCRIPTION
**Pull request by RadoslavK**
Fixes the #199

### CODE REVIEW

**Comment by ashmaroli** [comment]
To be honest, I'm not sure what the best route is here.. *revert the caching upstream or accept this patch here...*

Shipping this patch will solve the problem for Jekyll 3.8.x but.. I've already implemented caching for `site.documents` as well [for Jekyll 4.0 ](https://github.com/jekyll/jekyll/blob/1041f7672f3683062c3ff16667f957477ce73ced/lib/jekyll/site.rb#L335-L339)

@RadoslavK Will you be able run your set up with the **proposed patch here *and* `jekyll-4.0.0.pre.alpha1`**? If your local tests pass satisfactorily, this PR can be shipped, otherwise we may need to revert the caching at Jekyll itself.

**Comment by mattr-** [comment]
This is painful, but I'd rather see us revert the caching mechanism we added to Jekyll. It doesn't make sense to me to make plugins workaround problems we've introduced in the core.

**Comment by parkr** [comment]
I think removing the `docs_to_write` cache is the better move, but it requires a Jekyll update. I'm happy to do this as well to unblock folks.

**Comment by ashmaroli** [comment]
@parkr I volunteer to provide you with assistance. Should I submit a PR to Jekyll's `3.8.stable` branch?

**Comment by DirtyF** [comment]
@RadoslavK This will be fixed upstream in Jekyll core, thanks for reporting.

**Pull request closed without merging**
