### PR TITLE
remove spaces in redirect page

### PR DESCRIPTION
**Pull request by eksperimental**
rebased version of #61
no need to waste those precious bytes

### CODE REVIEW

**Comment by parkr** [comment]
Can you please update the spec? https://travis-ci.org/jekyll/jekyll-redirect-from/jobs/49713963

**Comment by eksperimental** [comment]
sorry i cloned from master.

**Comment by eksperimental** [comment]
got it.  isee what you mean by specs.. i call those "tests"

**Comment by parkr** [comment]
The change you made broke it. To have this pull request merged, you have to fix the spec too :)

**Pull request merged**
